web:
  restart: always
  build: .
  volumes:
    - ".:/code"
  ports:
    - "80:80"
  links:
    - blackfire
    - postgres
    - redis
  environment:
    - LARAVEL_ENV=local
    - POSTGRESQL_HOST=postgres
    - REDIS_HOST=redis

blackfire:
  image: blackfire/blackfire
  env_file: ./app/.env

postgres:
  image: jcalazan/postgresql
  ports:
    - "5432:5432"
  env_file: ./app/.env

redis:
  image: redis:2.8
  ports:
    - "6379:6379"
